# DVC Parameters

data:
  raw_dir: "ml/data/raw"
  processed_dir: "ml/data/processed"
  train_ratio: 0.7
  val_ratio: 0.1
  test_ratio: 0.2
  img_size: [224, 224]

model:
  name: "pneumonia_mobilenetv2"
  base_model: "mobilenetv2"
  num_classes: 2
  trainable_base: false

training:
  batch_size: 32
  epochs: 50
  learning_rate: 0.001
  early_stopping_patience: 10